### ISSUE TITLE
Seems there is somethong wrong with the choice feature.

### ISSUE THREAD

**Issue by fei0319** [Clouder0/AnkiImporter#2]
I just import from the given "ExampleDeck.apkg" and it can't work correctly.
[![g6JQdU.png](https://z3.ax1x.com/2021/05/15/g6JQdU.png)](https://imgtu.com/i/g6JQdU)

**Comment by Clouder0** [comment]
Preview can't work properly for this type of card.   
Try to study it directly.

**Comment by fei0319** [comment]
Orz Clouder!

**Comment by fei0319** [comment]
However, I find it still uncorrect when I study it directly.

**Comment by fei0319** [comment]
Just like this:
[![g6JOmV.png](https://z3.ax1x.com/2021/05/15/g6JOmV.png)](https://imgtu.com/i/g6JOmV)

**Comment by Clouder0** [comment]
> Just like this:
> [![g6JOmV.png](https://camo.githubusercontent.com/9d6be2ea2336e7c9b7620f836ebc8cbdea0bd1c2255d4b7216a6f9bb5f06792c/68747470733a2f2f7a332e617831782e636f6d2f323032312f30352f31352f67364a4f6d562e706e67)](https://imgtu.com/i/g6JOmV)

That's interesting. I reproduced it successfully and it seems that the template will only recognize `A.` and `A ` for an option's prefix and remove it, otherwise, it would be included in the text.  
I'd like to modify the related test cases to avoid misleading users.

For choices, just use `A ` or `A.` which is officially supported.

**Comment by fei0319** [comment]
Even demo(https://github.com/Clouder0/AnkiImporter/blob/main/doc/images/screenshot-2) is wrong, where A should be "asjdskladjkslajd" rather than "askldjsaljk".

**Comment by Clouder0** [comment]
> Even demo(https://github.com/Clouder0/AnkiImporter/blob/main/doc/images/screenshot-2) is wrong, where A should be "asjdskladjkslajd" rather than "askldjsaljk".

It's a feature actually. The intended obfuscation prevent users from reciting only the answer to the question.

**Comment by fei0319** [comment]
> 
> 
> > Even demo(https://github.com/Clouder0/AnkiImporter/blob/main/doc/images/screenshot-2) is wrong, where A should be "asjdskladjkslajd" rather than "askldjsaljk".
> 
> It's a feature actually. The intended obfuscation prevent users from reciting only the answer to the question.

I got it.
