### ISSUE TITLE
wish multiple blocks containing **sth.**  also may create one card instead of multiple cards 

### ISSUE THREAD

**Issue by kangdalei** [Clouder0/AnkiImporter#45]
## The alphabet starts with {{c1::a}} {{c2::b}} {{c1::a}}

=> 

one card:

The alphabet starts with [...] b [...]

and another card:

The alphabet starts with a [...] c

The c1 clozes are blocked out together.

**Comment by Clouder0** [comment]
I don't quite understand what you meant. For now, generating 'notes' in AnkiLink is block-based, which means that it is not straightforward to add multiple-block-one-note support.

If you want c1 clozes to be blocked out together, try `**[1]Cloze** and **[2]Cloze2** and **[1]Cloze**`.

**Comment by kangdalei** [comment]
Thanks! 

> **[1]Cloze** and **[2]Cloze2** and **[1]Cloze**

 it's just what I wanted.
